export interface Product {
  id: string
  name: string
  price: number
  category: string
  image: string
  discount?: number
  description: string
  colors: string[]
  sizes: string[]
}

export interface Event {
  id: string
  title: string
  description: string
  discountPercentage: number
  startDate: string
  endDate: string
  isActive: boolean
  applicableCategories: string[]
  bannerImage?: string
}

export interface AdminSettings {
  events: Event[]
  featuredCategories: string[]
  promotionalBanners: string[]
}

// Mock data for development - replace with actual Google Sheets API integration
const mockAdminSettings: AdminSettings = {
  events: [
    {
      id: "summer-sale-2025",
      title: "Summer Sale",
      description: "Up to 50% off summer collection",
      discountPercentage: 50,
      startDate: "2025-06-01",
      endDate: "2025-08-31",
      isActive: true,
      applicableCategories: ["T-Shirts", "Shorts", "Dresses"],
      bannerImage: "/summer-sale-banner.png",
    },
    {
      id: "new-arrivals-2025",
      title: "New Arrivals",
      description: "Fresh styles just in",
      discountPercentage: 20,
      startDate: "2025-01-01",
      endDate: "2025-12-31",
      isActive: true,
      applicableCategories: ["Hoodies", "Jackets"],
      bannerImage: "/new-arrivals-banner.png",
    },
  ],
  featuredCategories: ["T-Shirts", "Jeans", "Hoodies", "Dresses"],
  promotionalBanners: ["/summer-sale-banner.png", "/new-arrivals-banner.png"],
}

export const mockProducts: Product[] = [
  // T-Shirts with Summer Sale discount
  {
    id: "001",
    name: "Basic Cotton T-Shirt",
    price: 15.99,
    category: "T-Shirts",
    image: "/basic-cotton-t-shirt.png",
    discount: 50, // Applied from Summer Sale event
    description: "Comfortable cotton t-shirt perfect for everyday wear",
    colors: ["Black", "White", "Gray", "Navy"],
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "002",
    name: "Graphic Print Tee",
    price: 19.99,
    category: "T-Shirts",
    image: "/graphic-print-t-shirt.png",
    discount: 10,
    description: "Trendy graphic print t-shirt",
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "003",
    name: "V-Neck T-Shirt",
    price: 17.99,
    category: "T-Shirts",
    image: "/v-neck-t-shirt.png",
    description: "Classic v-neck style t-shirt",
    colors: ["White", "Black", "Gray", "Navy", "Burgundy"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "004",
    name: "Long Sleeve Tee",
    price: 22.99,
    category: "T-Shirts",
    image: "/long-sleeve-t-shirt.png",
    description: "Comfortable long sleeve t-shirt",
    colors: ["White", "Black", "Gray", "Navy"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "005",
    name: "Striped T-Shirt",
    price: 18.99,
    category: "T-Shirts",
    image: "/striped-t-shirt.png",
    discount: 15,
    description: "Classic striped pattern t-shirt",
    colors: ["Navy/White", "Black/White", "Red/White"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "006",
    name: "Pocket T-Shirt",
    price: 16.99,
    category: "T-Shirts",
    image: "/pocket-t-shirt.png",
    description: "Simple t-shirt with chest pocket",
    colors: ["White", "Black", "Gray", "Olive"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "007",
    name: "Henley T-Shirt",
    price: 21.99,
    category: "T-Shirts",
    image: "/henley-t-shirt.png",
    description: "Casual henley style t-shirt",
    colors: ["White", "Black", "Gray", "Navy"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "008",
    name: "Vintage Wash Tee",
    price: 24.99,
    category: "T-Shirts",
    image: "/vintage-wash-t-shirt.png",
    description: "Soft vintage washed t-shirt",
    colors: ["Faded Black", "Vintage Gray", "Washed Blue"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "009",
    name: "Crew Neck Tee",
    price: 14.99,
    category: "T-Shirts",
    image: "/crew-neck-t-shirt.png",
    description: "Classic crew neck t-shirt",
    colors: ["White", "Black", "Gray", "Navy", "Red"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "010",
    name: "Oversized T-Shirt",
    price: 19.99,
    category: "T-Shirts",
    image: "/oversized-t-shirt.png",
    discount: 20,
    description: "Trendy oversized fit t-shirt",
    colors: ["Black", "White", "Beige"],
    sizes: ["S", "M", "L", "XL"],
  },

  // Jeans (10 items)
  {
    id: "011",
    name: "Classic Straight Jeans",
    price: 49.99,
    category: "Jeans",
    image: "/straight-leg-jeans.png",
    description: "Timeless straight leg jeans",
    colors: ["Dark Blue", "Light Blue", "Black"],
    sizes: ["28", "30", "32", "34", "36", "38"],
  },
  {
    id: "012",
    name: "Skinny Fit Jeans",
    price: 54.99,
    category: "Jeans",
    image: "/skinny-fit-jeans.png",
    description: "Modern skinny fit jeans",
    colors: ["Dark Blue", "Black", "Gray"],
    sizes: ["28", "30", "32", "34", "36"],
  },
  {
    id: "013",
    name: "Relaxed Fit Jeans",
    price: 47.99,
    category: "Jeans",
    image: "/relaxed-fit-jeans.png",
    discount: 10,
    description: "Comfortable relaxed fit jeans",
    colors: ["Medium Blue", "Dark Blue", "Black"],
    sizes: ["30", "32", "34", "36", "38", "40"],
  },
  {
    id: "014",
    name: "Bootcut Jeans",
    price: 52.99,
    category: "Jeans",
    image: "/bootcut-jeans.png",
    description: "Classic bootcut style jeans",
    colors: ["Dark Blue", "Medium Blue"],
    sizes: ["28", "30", "32", "34", "36", "38"],
  },
  {
    id: "015",
    name: "Distressed Jeans",
    price: 59.99,
    category: "Jeans",
    image: "/distressed-ripped-jeans.png",
    description: "Trendy distressed denim jeans",
    colors: ["Light Blue", "Medium Blue"],
    sizes: ["28", "30", "32", "34", "36"],
  },
  {
    id: "016",
    name: "High Waist Jeans",
    price: 56.99,
    category: "Jeans",
    image: "/high-waist-jeans.png",
    description: "Flattering high waist jeans",
    colors: ["Dark Blue", "Black", "Light Blue"],
    sizes: ["26", "28", "30", "32", "34"],
  },
  {
    id: "017",
    name: "Tapered Jeans",
    price: 51.99,
    category: "Jeans",
    image: "/tapered-jeans.png",
    description: "Modern tapered fit jeans",
    colors: ["Dark Blue", "Black"],
    sizes: ["28", "30", "32", "34", "36"],
  },
  {
    id: "018",
    name: "Raw Denim Jeans",
    price: 69.99,
    category: "Jeans",
    image: "/raw-denim-jeans.png",
    discount: 15,
    description: "Premium raw denim jeans",
    colors: ["Indigo", "Black"],
    sizes: ["28", "30", "32", "34", "36"],
  },
  {
    id: "019",
    name: "Cropped Jeans",
    price: 45.99,
    category: "Jeans",
    image: "/cropped-ankle-jeans.png",
    description: "Stylish cropped ankle jeans",
    colors: ["Light Blue", "Dark Blue", "White"],
    sizes: ["26", "28", "30", "32", "34"],
  },
  {
    id: "020",
    name: "Wide Leg Jeans",
    price: 58.99,
    category: "Jeans",
    image: "/wide-leg-jeans.png",
    description: "Trendy wide leg jeans",
    colors: ["Light Blue", "Dark Blue"],
    sizes: ["26", "28", "30", "32", "34"],
  },

  // Shirts (10 items)
  {
    id: "021",
    name: "Dress Shirt White",
    price: 39.99,
    category: "Shirts",
    image: "/white-dress-shirt.png",
    description: "Classic white dress shirt",
    colors: ["White", "Light Blue", "Pink"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "022",
    name: "Casual Button Down",
    price: 34.99,
    category: "Shirts",
    image: "/casual-button-down-shirt.png",
    description: "Relaxed casual button down shirt",
    colors: ["Blue", "White", "Gray", "Green"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "023",
    name: "Flannel Shirt",
    price: 42.99,
    category: "Shirts",
    image: "/flannel-plaid-shirt.png",
    discount: 20,
    description: "Warm flannel plaid shirt",
    colors: ["Red/Black", "Blue/Black", "Green/Black"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "024",
    name: "Oxford Shirt",
    price: 37.99,
    category: "Shirts",
    image: "/oxford-button-shirt.png",
    description: "Classic oxford button shirt",
    colors: ["White", "Light Blue", "Pink", "Yellow"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "025",
    name: "Denim Shirt",
    price: 44.99,
    category: "Shirts",
    image: "/denim-chambray-shirt.png",
    description: "Casual denim chambray shirt",
    colors: ["Light Blue", "Dark Blue", "Black"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "026",
    name: "Linen Shirt",
    price: 46.99,
    category: "Shirts",
    image: "/placeholder.svg?height=300&width=300",
    description: "Breathable linen summer shirt",
    colors: ["White", "Beige", "Light Blue", "Pink"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "027",
    name: "Polo Shirt",
    price: 29.99,
    category: "Shirts",
    image: "/placeholder.svg?height=300&width=300",
    description: "Classic polo shirt",
    colors: ["Navy", "White", "Black", "Red", "Green"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "028",
    name: "Hawaiian Shirt",
    price: 35.99,
    category: "Shirts",
    image: "/placeholder.svg?height=300&width=300",
    discount: 10,
    description: "Fun tropical Hawaiian shirt",
    colors: ["Blue/Floral", "Black/Floral", "White/Floral"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "029",
    name: "Work Shirt",
    price: 41.99,
    category: "Shirts",
    image: "/placeholder.svg?height=300&width=300",
    description: "Durable work utility shirt",
    colors: ["Navy", "Gray", "Khaki"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "030",
    name: "Striped Shirt",
    price: 33.99,
    category: "Shirts",
    image: "/placeholder.svg?height=300&width=300",
    description: "Classic striped button shirt",
    colors: ["Blue/White", "Black/White", "Red/White"],
    sizes: ["S", "M", "L", "XL"],
  },

  // Hoodies (10 items)
  {
    id: "031",
    name: "Basic Pullover Hoodie",
    price: 45.99,
    category: "Hoodies",
    image: "/placeholder.svg?height=300&width=300",
    description: "Comfortable pullover hoodie",
    colors: ["Black", "Gray", "Navy", "White"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "032",
    name: "Zip-Up Hoodie",
    price: 49.99,
    category: "Hoodies",
    image: "/placeholder.svg?height=300&width=300",
    description: "Convenient zip-up hoodie",
    colors: ["Black", "Gray", "Navy", "Red"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "033",
    name: "Oversized Hoodie",
    price: 52.99,
    category: "Hoodies",
    image: "/placeholder.svg?height=300&width=300",
    discount: 15,
    description: "Trendy oversized fit hoodie",
    colors: ["Black", "Beige", "Gray"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "034",
    name: "Graphic Hoodie",
    price: 47.99,
    category: "Hoodies",
    image: "/placeholder.svg?height=300&width=300",
    description: "Cool graphic print hoodie",
    colors: ["Black", "White", "Gray"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "035",
    name: "Fleece Hoodie",
    price: 54.99,
    category: "Hoodies",
    image: "/placeholder.svg?height=300&width=300",
    description: "Warm fleece lined hoodie",
    colors: ["Black", "Gray", "Navy"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "036",
    name: "Cropped Hoodie",
    price: 43.99,
    category: "Hoodies",
    image: "/placeholder.svg?height=300&width=300",
    description: "Stylish cropped hoodie",
    colors: ["Black", "White", "Pink", "Gray"],
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "037",
    name: "Tech Fleece Hoodie",
    price: 69.99,
    category: "Hoodies",
    image: "/placeholder.svg?height=300&width=300",
    description: "Premium tech fleece hoodie",
    colors: ["Black", "Gray", "Navy"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "038",
    name: "Vintage Hoodie",
    price: 48.99,
    category: "Hoodies",
    image: "/placeholder.svg?height=300&width=300",
    discount: 10,
    description: "Retro vintage style hoodie",
    colors: ["Faded Black", "Vintage Gray", "Washed Blue"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "039",
    name: "Color Block Hoodie",
    price: 51.99,
    category: "Hoodies",
    image: "/placeholder.svg?height=300&width=300",
    description: "Modern color block hoodie",
    colors: ["Black/White", "Gray/Black", "Navy/White"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "040",
    name: "Sherpa Hoodie",
    price: 59.99,
    category: "Hoodies",
    image: "/placeholder.svg?height=300&width=300",
    description: "Ultra warm sherpa lined hoodie",
    colors: ["Black", "Brown", "Gray"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },

  // Jackets (10 items)
  {
    id: "041",
    name: "Denim Jacket",
    price: 65.99,
    category: "Jackets",
    image: "/placeholder.svg?height=300&width=300",
    description: "Classic denim jacket",
    colors: ["Light Blue", "Dark Blue", "Black"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "042",
    name: "Bomber Jacket",
    price: 72.99,
    category: "Jackets",
    image: "/placeholder.svg?height=300&width=300",
    description: "Stylish bomber jacket",
    colors: ["Black", "Navy", "Olive", "Burgundy"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "043",
    name: "Leather Jacket",
    price: 149.99,
    category: "Jackets",
    image: "/placeholder.svg?height=300&width=300",
    discount: 20,
    description: "Premium leather jacket",
    colors: ["Black", "Brown"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "044",
    name: "Windbreaker",
    price: 55.99,
    category: "Jackets",
    image: "/placeholder.svg?height=300&width=300",
    description: "Lightweight windbreaker jacket",
    colors: ["Black", "Navy", "Red", "White"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "045",
    name: "Puffer Jacket",
    price: 89.99,
    category: "Jackets",
    image: "/placeholder.svg?height=300&width=300",
    description: "Warm puffer jacket",
    colors: ["Black", "Navy", "Gray", "Red"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "046",
    name: "Track Jacket",
    price: 48.99,
    category: "Jackets",
    image: "/placeholder.svg?height=300&width=300",
    description: "Athletic track jacket",
    colors: ["Black", "Navy", "Red", "Blue"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "047",
    name: "Blazer",
    price: 95.99,
    category: "Jackets",
    image: "/placeholder.svg?height=300&width=300",
    description: "Smart casual blazer",
    colors: ["Navy", "Black", "Gray", "Brown"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "048",
    name: "Field Jacket",
    price: 78.99,
    category: "Jackets",
    image: "/placeholder.svg?height=300&width=300",
    discount: 15,
    description: "Utility field jacket",
    colors: ["Olive", "Black", "Khaki"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "049",
    name: "Coach Jacket",
    price: 62.99,
    category: "Jackets",
    image: "/placeholder.svg?height=300&width=300",
    description: "Classic coach jacket",
    colors: ["Black", "Navy", "White"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "050",
    name: "Varsity Jacket",
    price: 85.99,
    category: "Jackets",
    image: "/placeholder.svg?height=300&width=300",
    description: "Retro varsity jacket",
    colors: ["Black/White", "Navy/White", "Red/White"],
    sizes: ["S", "M", "L", "XL"],
  },

  // Pants (10 items)
  {
    id: "051",
    name: "Chino Pants",
    price: 42.99,
    category: "Pants",
    image: "/placeholder.svg?height=300&width=300",
    description: "Classic chino pants",
    colors: ["Khaki", "Navy", "Black", "Gray", "Olive"],
    sizes: ["28", "30", "32", "34", "36", "38"],
  },
  {
    id: "052",
    name: "Cargo Pants",
    price: 48.99,
    category: "Pants",
    image: "/placeholder.svg?height=300&width=300",
    description: "Utility cargo pants",
    colors: ["Khaki", "Black", "Olive", "Gray"],
    sizes: ["28", "30", "32", "34", "36", "38"],
  },
  {
    id: "053",
    name: "Dress Pants",
    price: 56.99,
    category: "Pants",
    image: "/placeholder.svg?height=300&width=300",
    description: "Formal dress pants",
    colors: ["Black", "Navy", "Gray", "Charcoal"],
    sizes: ["28", "30", "32", "34", "36", "38", "40"],
  },
  {
    id: "054",
    name: "Jogger Pants",
    price: 35.99,
    category: "Pants",
    image: "/placeholder.svg?height=300&width=300",
    discount: 10,
    description: "Comfortable jogger pants",
    colors: ["Black", "Gray", "Navy", "Olive"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "055",
    name: "Track Pants",
    price: 39.99,
    category: "Pants",
    image: "/placeholder.svg?height=300&width=300",
    description: "Athletic track pants",
    colors: ["Black", "Navy", "Red", "Blue"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "056",
    name: "Corduroy Pants",
    price: 52.99,
    category: "Pants",
    image: "/placeholder.svg?height=300&width=300",
    description: "Textured corduroy pants",
    colors: ["Brown", "Navy", "Black", "Olive"],
    sizes: ["28", "30", "32", "34", "36"],
  },
  {
    id: "057",
    name: "Linen Pants",
    price: 49.99,
    category: "Pants",
    image: "/placeholder.svg?height=300&width=300",
    description: "Breathable linen pants",
    colors: ["Beige", "White", "Navy", "Olive"],
    sizes: ["28", "30", "32", "34", "36"],
  },
  {
    id: "058",
    name: "Wide Leg Pants",
    price: 54.99,
    category: "Pants",
    image: "/placeholder.svg?height=300&width=300",
    description: "Trendy wide leg pants",
    colors: ["Black", "Navy", "Beige", "Gray"],
    sizes: ["26", "28", "30", "32", "34"],
  },
  {
    id: "059",
    name: "Cropped Pants",
    price: 44.99,
    category: "Pants",
    image: "/placeholder.svg?height=300&width=300",
    discount: 15,
    description: "Stylish cropped pants",
    colors: ["Black", "Navy", "Beige", "White"],
    sizes: ["26", "28", "30", "32", "34"],
  },
  {
    id: "060",
    name: "Pleated Pants",
    price: 58.99,
    category: "Pants",
    image: "/placeholder.svg?height=300&width=300",
    description: "Classic pleated pants",
    colors: ["Black", "Navy", "Gray", "Brown"],
    sizes: ["28", "30", "32", "34", "36", "38"],
  },

  // Shorts (10 items)
  {
    id: "061",
    name: "Chino Shorts",
    price: 28.99,
    category: "Shorts",
    image: "/placeholder.svg?height=300&width=300",
    description: "Classic chino shorts",
    colors: ["Khaki", "Navy", "Black", "White", "Olive"],
    sizes: ["28", "30", "32", "34", "36"],
  },
  {
    id: "062",
    name: "Denim Shorts",
    price: 32.99,
    category: "Shorts",
    image: "/placeholder.svg?height=300&width=300",
    description: "Casual denim shorts",
    colors: ["Light Blue", "Dark Blue", "Black"],
    sizes: ["28", "30", "32", "34", "36"],
  },
  {
    id: "063",
    name: "Athletic Shorts",
    price: 24.99,
    category: "Shorts",
    image: "/placeholder.svg?height=300&width=300",
    description: "Performance athletic shorts",
    colors: ["Black", "Navy", "Red", "Blue", "Gray"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "064",
    name: "Board Shorts",
    price: 35.99,
    category: "Shorts",
    image: "/placeholder.svg?height=300&width=300",
    description: "Quick-dry board shorts",
    colors: ["Blue", "Black", "Red", "Green"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "065",
    name: "Cargo Shorts",
    price: 34.99,
    category: "Shorts",
    image: "/placeholder.svg?height=300&width=300",
    discount: 10,
    description: "Utility cargo shorts",
    colors: ["Khaki", "Black", "Olive", "Gray"],
    sizes: ["28", "30", "32", "34", "36"],
  },
  {
    id: "066",
    name: "Sweat Shorts",
    price: 22.99,
    category: "Shorts",
    image: "/placeholder.svg?height=300&width=300",
    description: "Comfortable sweat shorts",
    colors: ["Black", "Gray", "Navy", "White"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "067",
    name: "Linen Shorts",
    price: 31.99,
    category: "Shorts",
    image: "/placeholder.svg?height=300&width=300",
    description: "Breathable linen shorts",
    colors: ["Beige", "White", "Navy", "Light Blue"],
    sizes: ["28", "30", "32", "34", "36"],
  },
  {
    id: "068",
    name: "Basketball Shorts",
    price: 26.99,
    category: "Shorts",
    image: "/placeholder.svg?height=300&width=300",
    description: "Mesh basketball shorts",
    colors: ["Black", "Red", "Blue", "White"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "069",
    name: "Tailored Shorts",
    price: 38.99,
    category: "Shorts",
    image: "/placeholder.svg?height=300&width=300",
    description: "Smart tailored shorts",
    colors: ["Navy", "Black", "Gray", "Khaki"],
    sizes: ["28", "30", "32", "34", "36"],
  },
  {
    id: "070",
    name: "Running Shorts",
    price: 27.99,
    category: "Shorts",
    image: "/placeholder.svg?height=300&width=300",
    discount: 15,
    description: "Lightweight running shorts",
    colors: ["Black", "Navy", "Red", "Blue"],
    sizes: ["S", "M", "L", "XL"],
  },

  // Dresses (10 items)
  {
    id: "071",
    name: "Summer Dress",
    price: 45.99,
    category: "Dresses",
    image: "/placeholder.svg?height=300&width=300",
    description: "Light and airy summer dress",
    colors: ["White", "Blue", "Pink", "Yellow"],
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "072",
    name: "Maxi Dress",
    price: 52.99,
    category: "Dresses",
    image: "/placeholder.svg?height=300&width=300",
    description: "Elegant floor-length maxi dress",
    colors: ["Black", "Navy", "Burgundy", "Green"],
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "073",
    name: "Cocktail Dress",
    price: 68.99,
    category: "Dresses",
    image: "/placeholder.svg?height=300&width=300",
    discount: 20,
    description: "Sophisticated cocktail dress",
    colors: ["Black", "Navy", "Red", "Emerald"],
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "074",
    name: "Casual Dress",
    price: 38.99,
    category: "Dresses",
    image: "/placeholder.svg?height=300&width=300",
    description: "Comfortable everyday dress",
    colors: ["Gray", "Navy", "Black", "Olive"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    id: "075",
    name: "Wrap Dress",
    price: 49.99,
    category: "Dresses",
    image: "/placeholder.svg?height=300&width=300",
    description: "Flattering wrap-style dress",
    colors: ["Black", "Navy", "Red", "Floral"],
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "076",
    name: "Shirt Dress",
    price: 42.99,
    category: "Dresses",
    image: "/placeholder.svg?height=300&width=300",
    description: "Classic shirt-style dress",
    colors: ["White", "Blue", "Striped", "Khaki"],
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "077",
    name: "A-Line Dress",
    price: 46.99,
    category: "Dresses",
    image: "/placeholder.svg?height=300&width=300",
    description: "Timeless A-line dress",
    colors: ["Black", "Navy", "Red", "Pink"],
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "078",
    name: "Bodycon Dress",
    price: 39.99,
    category: "Dresses",
    image: "/placeholder.svg?height=300&width=300",
    description: "Form-fitting bodycon dress",
    colors: ["Black", "Red", "Navy", "White"],
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "079",
    name: "Midi Dress",
    price: 44.99,
    category: "Dresses",
    image: "/placeholder.svg?height=300&width=300",
    description: "Versatile midi-length dress",
    colors: ["Black", "Navy", "Burgundy", "Green"],
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "080",
    name: "Off-Shoulder Dress",
    price: 51.99,
    category: "Dresses",
    image: "/placeholder.svg?height=300&width=300",
    description: "Trendy off-shoulder dress",
    colors: ["White", "Black", "Red", "Blue"],
    sizes: ["XS", "S", "M", "L", "XL"],
  },

  // Accessories (20 items)
  {
    id: "081",
    name: "Leather Belt",
    price: 24.99,
    category: "Accessories",
    image: "/placeholder.svg?height=300&width=300",
    description: "Classic leather belt",
    colors: ["Black", "Brown", "Tan"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "082",
    name: "Baseball Cap",
    price: 18.99,
    category: "Accessories",
    image: "/placeholder.svg?height=300&width=300",
    description: "Adjustable baseball cap",
    colors: ["Black", "Navy", "White", "Red"],
    sizes: ["One Size"],
  },
  {
    id: "083",
    name: "Beanie Hat",
    price: 15.99,
    category: "Accessories",
    image: "/placeholder.svg?height=300&width=300",
    description: "Warm knit beanie",
    colors: ["Black", "Gray", "Navy", "Red"],
    sizes: ["One Size"],
  },
  {
    id: "084",
    name: "Sunglasses",
    price: 32.99,
    category: "Accessories",
    image: "/placeholder.svg?height=300&width=300",
    discount: 15,
    description: "Stylish sunglasses",
    colors: ["Black", "Brown", "Silver"],
    sizes: ["One Size"],
  },
  {
    id: "085",
    name: "Backpack",
    price: 49.99,
    category: "Accessories",
    image: "/placeholder.svg?height=300&width=300",
    description: "Durable everyday backpack",
    colors: ["Black", "Navy", "Gray", "Olive"],
    sizes: ["One Size"],
  },
  {
    id: "086",
    name: "Wallet",
    price: 28.99,
    category: "Accessories",
    image: "/placeholder.svg?height=300&width=300",
    description: "Genuine leather wallet",
    colors: ["Black", "Brown", "Tan"],
    sizes: ["One Size"],
  },
  {
    id: "087",
    name: "Watch",
    price: 89.99,
    category: "Accessories",
    image: "/placeholder.svg?height=300&width=300",
    description: "Classic analog watch",
    colors: ["Silver", "Gold", "Black"],
    sizes: ["One Size"],
  },
  {
    id: "088",
    name: "Scarf",
    price: 22.99,
    category: "Accessories",
    image: "/placeholder.svg?height=300&width=300",
    description: "Warm winter scarf",
    colors: ["Black", "Gray", "Navy", "Red"],
    sizes: ["One Size"],
  },
  {
    id: "089",
    name: "Gloves",
    price: 19.99,
    category: "Accessories",
    image: "/placeholder.svg?height=300&width=300",
    discount: 10,
    description: "Insulated winter gloves",
    colors: ["Black", "Gray", "Navy"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "090",
    name: "Tie",
    price: 16.99,
    category: "Accessories",
    image: "/placeholder.svg?height=300&width=300",
    description: "Silk dress tie",
    colors: ["Navy", "Black", "Red", "Blue"],
    sizes: ["One Size"],
  },
  {
    id: "091",
    name: "Bow Tie",
    price: 14.99,
    category: "Accessories",
    image: "/placeholder.svg?height=300&width=300",
    description: "Classic bow tie",
    colors: ["Black", "Navy", "Red", "White"],
    sizes: ["One Size"],
  },
  {
    id: "092",
    name: "Suspenders",
    price: 21.99,
    category: "Accessories",
    image: "/placeholder.svg?height=300&width=300",
    description: "Adjustable suspenders",
    colors: ["Black", "Brown", "Navy"],
    sizes: ["One Size"],
  },
  {
    id: "093",
    name: "Messenger Bag",
    price: 42.99,
    category: "Accessories",
    image: "/placeholder.svg?height=300&width=300",
    description: "Canvas messenger bag",
    colors: ["Black", "Brown", "Olive", "Navy"],
    sizes: ["One Size"],
  },
  {
    id: "094",
    name: "Bucket Hat",
    price: 17.99,
    category: "Accessories",
    image: "/placeholder.svg?height=300&width=300",
    description: "Casual bucket hat",
    colors: ["Black", "Khaki", "Navy", "White"],
    sizes: ["S/M", "L/XL"],
  },
  {
    id: "095",
    name: "Chain Necklace",
    price: 25.99,
    category: "Accessories",
    image: "/placeholder.svg?height=300&width=300",
    discount: 20,
    description: "Stainless steel chain",
    colors: ["Silver", "Gold", "Black"],
    sizes: ["One Size"],
  },
  {
    id: "096",
    name: "Ring",
    price: 12.99,
    category: "Accessories",
    image: "/placeholder.svg?height=300&width=300",
    description: "Simple band ring",
    colors: ["Silver", "Gold", "Black"],
    sizes: ["6", "7", "8", "9", "10"],
  },
  {
    id: "097",
    name: "Bracelet",
    price: 18.99,
    category: "Accessories",
    image: "/placeholder.svg?height=300&width=300",
    description: "Leather bracelet",
    colors: ["Black", "Brown", "Tan"],
    sizes: ["S", "M", "L"],
  },
  {
    id: "098",
    name: "Keychain",
    price: 8.99,
    category: "Accessories",
    image: "/placeholder.svg?height=300&width=300",
    description: "Metal keychain",
    colors: ["Silver", "Black", "Gold"],
    sizes: ["One Size"],
  },
  {
    id: "099",
    name: "Phone Case",
    price: 14.99,
    category: "Accessories",
    image: "/placeholder.svg?height=300&width=300",
    description: "Protective phone case",
    colors: ["Black", "Clear", "Blue", "Red"],
    sizes: ["iPhone", "Samsung"],
  },
  {
    id: "100",
    name: "Tote Bag",
    price: 26.99,
    category: "Accessories",
    image: "/placeholder.svg?height=300&width=300",
    description: "Canvas tote bag",
    colors: ["Black", "White", "Navy", "Beige"],
    sizes: ["One Size"],
  },
]

// Function to fetch products from Google Sheets
export async function fetchProducts(): Promise<Product[]> {
  // TODO: Implement actual Google Sheets API integration
  // For now, return mock data
  return new Promise((resolve) => {
    setTimeout(() => resolve(mockProducts), 500)
  })
}

// Function to get products by category
export function getProductsByCategory(products: Product[], category?: string): Product[] {
  if (!category) return products
  return products.filter((product) => product.category.toLowerCase() === category.toLowerCase())
}

// Function to search products
export function searchProducts(products: Product[], query: string): Product[] {
  if (!query) return products
  const lowercaseQuery = query.toLowerCase()
  return products.filter(
    (product) =>
      product.name.toLowerCase().includes(lowercaseQuery) ||
      product.description.toLowerCase().includes(lowercaseQuery) ||
      product.category.toLowerCase().includes(lowercaseQuery),
  )
}

// Function to get products by event ID for proper discount linking
export function getProductsByEvent(products: Product[], eventId: string): Product[] {
  const event = mockAdminSettings.events.find((e) => e.id === eventId)
  if (!event) return []

  return products.filter(
    (product) => event.applicableCategories.includes(product.category) && product.discount && product.discount > 0,
  )
}

// Function to get event by ID for banner linking
export function getEventById(eventId: string): Event | undefined {
  return mockAdminSettings.events.find((event) => event.id === eventId)
}

// Function to get active events and apply discounts
export const getActiveEvents = (): Event[] => {
  const currentDate = new Date().toISOString().split("T")[0]
  return mockAdminSettings.events.filter(
    (event) => event.isActive && currentDate >= event.startDate && currentDate <= event.endDate,
  )
}

export const getAdminSettings = (): AdminSettings => {
  return mockAdminSettings
}

export const getProducts = (): Product[] => {
  const activeEvents = getActiveEvents()

  return mockProducts.map((product) => {
    const applicableEvent = activeEvents.find((event) => event.applicableCategories.includes(product.category))

    return {
      ...product,
      discount: applicableEvent ? applicableEvent.discountPercentage : product.discount,
    }
  })
}
